### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by bruce-wmm** [crazypoo/AV#1]
下载以后不能打开

**Comment by crazypoo** [comment]
你好，写了新手教程为什么就是不看

**Comment by crazypoo** [comment]
你好，写了教程为什么就是不看？

**Comment by bruce-wmm** [comment]
应该是xcode版本的问题吧

**Comment by bruce-wmm** [comment]
我的是xcode9.2

**Comment by crazypoo** [comment]
怎么可能呢,肯定是你打开文件的方式错了,你是做ios开发的吗

**Comment by bruce-wmm** [comment]
因为, 我朋友的xcode就可以打开, 同样的代码, 他能打开, 我不能, 区别就是xcode版本不一样

**Comment by crazypoo** [comment]
是编译不了还是怎么样

**Comment by bruce-wmm** [comment]
直接打不开,报红提示 The file couldn’t be opened.,  我改天升级一下xcode吧, 最近这种情况碰到很多次了,
